version: "3"
services:
  db:
    image: postgres:9.4
    expose:
      - 5432
    environment:
      POSTGRES_USER: "editor"
      POSTGRES_PASSWORD: "N0A8KHWWHMjRBTrc8UjL"

  engine:
    image: ghcr.io/servicecutter/engine
    expose:
     - 8080
    depends_on:
     - db
 
  editor:
    image: ghcr.io/servicecutter/editor
    ports:
     - "8080:8080"
    links:
      - db
      - engine
    environment:
      POSTGRES_USER: "editor"
      POSTGRES_PASSWORD: "N0A8KHWWHMjRBTrc8UjL"
      ENGINE_HOST: "engine"
      ENGINE_PORT: "8080"
    depends_on:
     - engine