// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Data;

namespace ProductService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ProductService.Data.Dto.ProductDto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Color = "plum",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Sleek Concrete Salad",
                            Price = "269.26",
                            ProductId = "0",
                            Quantity = 64,
                            Size = "small"
                        },
                        new
                        {
                            Id = 1,
                            Color = "white",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Tasty Wooden Towels",
                            Price = "207.41",
                            ProductId = "1",
                            Quantity = 24,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 2,
                            Color = "silver",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Tasty Plastic Shoes",
                            Price = "170.13",
                            ProductId = "2",
                            Quantity = 40,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 3,
                            Color = "teal",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Tasty Granite Salad",
                            Price = "966.68",
                            ProductId = "3",
                            Quantity = 64,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 4,
                            Color = "red",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Small Plastic Chips",
                            Price = "843.60",
                            ProductId = "4",
                            Quantity = 72,
                            Size = "large"
                        },
                        new
                        {
                            Id = 5,
                            Color = "lavender",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Ergonomic Plastic Cheese",
                            Price = "156.93",
                            ProductId = "5",
                            Quantity = 20,
                            Size = "large"
                        },
                        new
                        {
                            Id = 6,
                            Color = "fuchsia",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Rustic Rubber Fish",
                            Price = "144.24",
                            ProductId = "6",
                            Quantity = 96,
                            Size = "small"
                        },
                        new
                        {
                            Id = 7,
                            Color = "lime",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Intelligent Granite Chicken",
                            Price = "118.33",
                            ProductId = "7",
                            Quantity = 74,
                            Size = "small"
                        },
                        new
                        {
                            Id = 8,
                            Color = "fuchsia",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Tasty Metal Mouse",
                            Price = "325.75",
                            ProductId = "8",
                            Quantity = 83,
                            Size = "large"
                        },
                        new
                        {
                            Id = 9,
                            Color = "mint green",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Small Granite Gloves",
                            Price = "12.34",
                            ProductId = "9",
                            Quantity = 62,
                            Size = "large"
                        },
                        new
                        {
                            Id = 10,
                            Color = "ivory",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Licensed Metal Shoes",
                            Price = "455.13",
                            ProductId = "10",
                            Quantity = 21,
                            Size = "small"
                        },
                        new
                        {
                            Id = 11,
                            Color = "white",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Gorgeous Metal Shoes",
                            Price = "317.14",
                            ProductId = "11",
                            Quantity = 64,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 12,
                            Color = "sky blue",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Licensed Fresh Bike",
                            Price = "262.00",
                            ProductId = "12",
                            Quantity = 50,
                            Size = "small"
                        },
                        new
                        {
                            Id = 13,
                            Color = "gold",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Rustic Soft Salad",
                            Price = "683.94",
                            ProductId = "13",
                            Quantity = 63,
                            Size = "large"
                        },
                        new
                        {
                            Id = 14,
                            Color = "violet",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Gorgeous Rubber Sausages",
                            Price = "415.41",
                            ProductId = "14",
                            Quantity = 60,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 15,
                            Color = "pink",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Refined Fresh Hat",
                            Price = "348.91",
                            ProductId = "15",
                            Quantity = 37,
                            Size = "large"
                        },
                        new
                        {
                            Id = 16,
                            Color = "gold",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Refined Steel Bacon",
                            Price = "679.32",
                            ProductId = "16",
                            Quantity = 63,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 17,
                            Color = "lime",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Awesome Granite Car",
                            Price = "546.77",
                            ProductId = "17",
                            Quantity = 59,
                            Size = "large"
                        },
                        new
                        {
                            Id = 18,
                            Color = "teal",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Licensed Steel Pants",
                            Price = "326.63",
                            ProductId = "18",
                            Quantity = 64,
                            Size = "large"
                        },
                        new
                        {
                            Id = 19,
                            Color = "green",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Intelligent Granite Chicken",
                            Price = "586.96",
                            ProductId = "19",
                            Quantity = 85,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 20,
                            Color = "gold",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Small Cotton Bacon",
                            Price = "299.65",
                            ProductId = "20",
                            Quantity = 38,
                            Size = "small"
                        },
                        new
                        {
                            Id = 21,
                            Color = "white",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Intelligent Frozen Car",
                            Price = "601.13",
                            ProductId = "21",
                            Quantity = 83,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 22,
                            Color = "red",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Unbranded Metal Soap",
                            Price = "301.23",
                            ProductId = "22",
                            Quantity = 65,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 23,
                            Color = "blue",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Ergonomic Cotton Shirt",
                            Price = "471.06",
                            ProductId = "23",
                            Quantity = 6,
                            Size = "large"
                        },
                        new
                        {
                            Id = 24,
                            Color = "sky blue",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Intelligent Soft Soap",
                            Price = "65.18",
                            ProductId = "24",
                            Quantity = 92,
                            Size = "large"
                        },
                        new
                        {
                            Id = 25,
                            Color = "sky blue",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Ergonomic Fresh Shirt",
                            Price = "401.33",
                            ProductId = "25",
                            Quantity = 60,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 26,
                            Color = "blue",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Ergonomic Steel Sausages",
                            Price = "5.11",
                            ProductId = "26",
                            Quantity = 62,
                            Size = "small"
                        },
                        new
                        {
                            Id = 27,
                            Color = "olive",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Sleek Steel Ball",
                            Price = "224.87",
                            ProductId = "27",
                            Quantity = 20,
                            Size = "large"
                        },
                        new
                        {
                            Id = 28,
                            Color = "fuchsia",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Incredible Plastic Soap",
                            Price = "828.23",
                            ProductId = "28",
                            Quantity = 57,
                            Size = "large"
                        },
                        new
                        {
                            Id = 29,
                            Color = "tan",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Practical Steel Hat",
                            Price = "435.53",
                            ProductId = "29",
                            Quantity = 65,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 30,
                            Color = "orange",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Gorgeous Concrete Chips",
                            Price = "687.17",
                            ProductId = "30",
                            Quantity = 2,
                            Size = "small"
                        },
                        new
                        {
                            Id = 31,
                            Color = "green",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Refined Metal Table",
                            Price = "612.55",
                            ProductId = "31",
                            Quantity = 37,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 32,
                            Color = "green",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Incredible Metal Ball",
                            Price = "281.77",
                            ProductId = "32",
                            Quantity = 69,
                            Size = "small"
                        },
                        new
                        {
                            Id = 33,
                            Color = "salmon",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Licensed Rubber Bike",
                            Price = "479.83",
                            ProductId = "33",
                            Quantity = 19,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 34,
                            Color = "teal",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Gorgeous Concrete Sausages",
                            Price = "114.09",
                            ProductId = "34",
                            Quantity = 63,
                            Size = "small"
                        },
                        new
                        {
                            Id = 35,
                            Color = "turquoise",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Licensed Steel Chicken",
                            Price = "853.46",
                            ProductId = "35",
                            Quantity = 77,
                            Size = "small"
                        },
                        new
                        {
                            Id = 36,
                            Color = "fuchsia",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Incredible Concrete Gloves",
                            Price = "56.76",
                            ProductId = "36",
                            Quantity = 98,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 37,
                            Color = "blue",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Practical Cotton Mouse",
                            Price = "40.45",
                            ProductId = "37",
                            Quantity = 3,
                            Size = "large"
                        },
                        new
                        {
                            Id = 38,
                            Color = "pink",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Practical Plastic Computer",
                            Price = "828.14",
                            ProductId = "38",
                            Quantity = 4,
                            Size = "large"
                        },
                        new
                        {
                            Id = 39,
                            Color = "blue",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Generic Frozen Salad",
                            Price = "131.08",
                            ProductId = "39",
                            Quantity = 45,
                            Size = "large"
                        },
                        new
                        {
                            Id = 40,
                            Color = "red",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Sleek Fresh Pizza",
                            Price = "858.39",
                            ProductId = "40",
                            Quantity = 85,
                            Size = "large"
                        },
                        new
                        {
                            Id = 41,
                            Color = "white",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Handcrafted Concrete Mouse",
                            Price = "901.44",
                            ProductId = "41",
                            Quantity = 43,
                            Size = "small"
                        },
                        new
                        {
                            Id = 42,
                            Color = "green",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Awesome Steel Gloves",
                            Price = "249.62",
                            ProductId = "42",
                            Quantity = 78,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 43,
                            Color = "green",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Refined Cotton Gloves",
                            Price = "737.38",
                            ProductId = "43",
                            Quantity = 4,
                            Size = "small"
                        },
                        new
                        {
                            Id = 44,
                            Color = "yellow",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Unbranded Concrete Towels",
                            Price = "203.10",
                            ProductId = "44",
                            Quantity = 98,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 45,
                            Color = "orchid",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Rustic Frozen Pants",
                            Price = "450.09",
                            ProductId = "45",
                            Quantity = 92,
                            Size = "small"
                        },
                        new
                        {
                            Id = 46,
                            Color = "silver",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Awesome Cotton Pizza",
                            Price = "908.28",
                            ProductId = "46",
                            Quantity = 83,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 47,
                            Color = "lime",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Generic Metal Chips",
                            Price = "677.00",
                            ProductId = "47",
                            Quantity = 49,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 48,
                            Color = "blue",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Fantastic Soft Hat",
                            Price = "923.34",
                            ProductId = "48",
                            Quantity = 0,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 49,
                            Color = "tan",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Gorgeous Wooden Tuna",
                            Price = "488.55",
                            ProductId = "49",
                            Quantity = 80,
                            Size = "large"
                        },
                        new
                        {
                            Id = 50,
                            Color = "orange",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Licensed Soft Hat",
                            Price = "682.84",
                            ProductId = "50",
                            Quantity = 81,
                            Size = "large"
                        },
                        new
                        {
                            Id = 51,
                            Color = "red",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Small Wooden Pants",
                            Price = "230.03",
                            ProductId = "51",
                            Quantity = 80,
                            Size = "small"
                        },
                        new
                        {
                            Id = 52,
                            Color = "black",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Tasty Soft Towels",
                            Price = "636.55",
                            ProductId = "52",
                            Quantity = 15,
                            Size = "small"
                        },
                        new
                        {
                            Id = 53,
                            Color = "orchid",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Fantastic Frozen Towels",
                            Price = "455.95",
                            ProductId = "53",
                            Quantity = 54,
                            Size = "small"
                        },
                        new
                        {
                            Id = 54,
                            Color = "violet",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Incredible Wooden Fish",
                            Price = "111.97",
                            ProductId = "54",
                            Quantity = 19,
                            Size = "small"
                        },
                        new
                        {
                            Id = 55,
                            Color = "mint green",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Tasty Plastic Chips",
                            Price = "578.13",
                            ProductId = "55",
                            Quantity = 39,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 56,
                            Color = "white",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Refined Rubber Pizza",
                            Price = "150.35",
                            ProductId = "56",
                            Quantity = 92,
                            Size = "large"
                        },
                        new
                        {
                            Id = 57,
                            Color = "purple",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Generic Cotton Table",
                            Price = "760.79",
                            ProductId = "57",
                            Quantity = 31,
                            Size = "small"
                        },
                        new
                        {
                            Id = 58,
                            Color = "teal",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Incredible Steel Table",
                            Price = "468.98",
                            ProductId = "58",
                            Quantity = 53,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 59,
                            Color = "blue",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Practical Concrete Keyboard",
                            Price = "569.80",
                            ProductId = "59",
                            Quantity = 9,
                            Size = "large"
                        },
                        new
                        {
                            Id = 60,
                            Color = "lime",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Generic Rubber Tuna",
                            Price = "658.77",
                            ProductId = "60",
                            Quantity = 56,
                            Size = "small"
                        },
                        new
                        {
                            Id = 61,
                            Color = "fuchsia",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Handcrafted Rubber Towels",
                            Price = "585.61",
                            ProductId = "61",
                            Quantity = 13,
                            Size = "small"
                        },
                        new
                        {
                            Id = 62,
                            Color = "green",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Incredible Cotton Car",
                            Price = "728.19",
                            ProductId = "62",
                            Quantity = 13,
                            Size = "large"
                        },
                        new
                        {
                            Id = 63,
                            Color = "indigo",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Small Steel Shoes",
                            Price = "796.80",
                            ProductId = "63",
                            Quantity = 55,
                            Size = "large"
                        },
                        new
                        {
                            Id = 64,
                            Color = "pink",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Awesome Plastic Chicken",
                            Price = "995.85",
                            ProductId = "64",
                            Quantity = 90,
                            Size = "large"
                        },
                        new
                        {
                            Id = 65,
                            Color = "tan",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Practical Concrete Pizza",
                            Price = "561.54",
                            ProductId = "65",
                            Quantity = 100,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 66,
                            Color = "grey",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Incredible Cotton Bacon",
                            Price = "486.40",
                            ProductId = "66",
                            Quantity = 28,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 67,
                            Color = "ivory",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Rustic Fresh Shoes",
                            Price = "648.72",
                            ProductId = "67",
                            Quantity = 54,
                            Size = "large"
                        },
                        new
                        {
                            Id = 68,
                            Color = "red",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Ergonomic Metal Soap",
                            Price = "362.32",
                            ProductId = "68",
                            Quantity = 41,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 69,
                            Color = "silver",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Fantastic Rubber Chicken",
                            Price = "343.16",
                            ProductId = "69",
                            Quantity = 55,
                            Size = "large"
                        },
                        new
                        {
                            Id = 70,
                            Color = "violet",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Tasty Wooden Mouse",
                            Price = "928.94",
                            ProductId = "70",
                            Quantity = 61,
                            Size = "large"
                        },
                        new
                        {
                            Id = 71,
                            Color = "teal",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Tasty Fresh Fish",
                            Price = "532.60",
                            ProductId = "71",
                            Quantity = 71,
                            Size = "large"
                        },
                        new
                        {
                            Id = 72,
                            Color = "turquoise",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Small Granite Salad",
                            Price = "999.40",
                            ProductId = "72",
                            Quantity = 80,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 73,
                            Color = "olive",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Rustic Frozen Salad",
                            Price = "775.72",
                            ProductId = "73",
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 74,
                            Color = "indigo",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Sleek Soft Towels",
                            Price = "77.04",
                            ProductId = "74",
                            Quantity = 23,
                            Size = "large"
                        },
                        new
                        {
                            Id = 75,
                            Color = "plum",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Practical Soft Shirt",
                            Price = "821.84",
                            ProductId = "75",
                            Quantity = 46,
                            Size = "large"
                        },
                        new
                        {
                            Id = 76,
                            Color = "tan",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Sleek Concrete Shoes",
                            Price = "234.09",
                            ProductId = "76",
                            Quantity = 42,
                            Size = "large"
                        },
                        new
                        {
                            Id = 77,
                            Color = "sky blue",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Ergonomic Fresh Table",
                            Price = "518.72",
                            ProductId = "77",
                            Quantity = 54,
                            Size = "small"
                        },
                        new
                        {
                            Id = 78,
                            Color = "teal",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Tasty Steel Mouse",
                            Price = "288.51",
                            ProductId = "78",
                            Quantity = 19,
                            Size = "small"
                        },
                        new
                        {
                            Id = 79,
                            Color = "fuchsia",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Handcrafted Steel Pants",
                            Price = "925.14",
                            ProductId = "79",
                            Quantity = 96,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 80,
                            Color = "salmon",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Intelligent Steel Hat",
                            Price = "239.14",
                            ProductId = "80",
                            Quantity = 82,
                            Size = "large"
                        },
                        new
                        {
                            Id = 81,
                            Color = "turquoise",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Unbranded Concrete Keyboard",
                            Price = "287.07",
                            ProductId = "81",
                            Quantity = 0,
                            Size = "large"
                        },
                        new
                        {
                            Id = 82,
                            Color = "black",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Ergonomic Concrete Shoes",
                            Price = "145.38",
                            ProductId = "82",
                            Quantity = 23,
                            Size = "small"
                        },
                        new
                        {
                            Id = 83,
                            Color = "plum",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Handcrafted Steel Fish",
                            Price = "317.48",
                            ProductId = "83",
                            Quantity = 51,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 84,
                            Color = "lavender",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Handcrafted Soft Pants",
                            Price = "179.47",
                            ProductId = "84",
                            Quantity = 26,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 85,
                            Color = "cyan",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Licensed Concrete Gloves",
                            Price = "677.64",
                            ProductId = "85",
                            Quantity = 71,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 86,
                            Color = "plum",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Fantastic Wooden Pizza",
                            Price = "743.42",
                            ProductId = "86",
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 87,
                            Color = "azure",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Ergonomic Fresh Keyboard",
                            Price = "103.68",
                            ProductId = "87",
                            Quantity = 26,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 88,
                            Color = "magenta",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Rustic Rubber Gloves",
                            Price = "724.42",
                            ProductId = "88",
                            Quantity = 37,
                            Size = "large"
                        },
                        new
                        {
                            Id = 89,
                            Color = "pink",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Gorgeous Frozen Table",
                            Price = "923.85",
                            ProductId = "89",
                            Quantity = 13,
                            Size = "small"
                        },
                        new
                        {
                            Id = 90,
                            Color = "black",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Handcrafted Plastic Computer",
                            Price = "305.67",
                            ProductId = "90",
                            Quantity = 7,
                            Size = "small"
                        },
                        new
                        {
                            Id = 91,
                            Color = "green",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Practical Soft Mouse",
                            Price = "115.88",
                            ProductId = "91",
                            Quantity = 79,
                            Size = "large"
                        },
                        new
                        {
                            Id = 92,
                            Color = "olive",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Fantastic Cotton Towels",
                            Price = "727.33",
                            ProductId = "92",
                            Quantity = 15,
                            Size = "small"
                        },
                        new
                        {
                            Id = 93,
                            Color = "lavender",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Awesome Rubber Cheese",
                            Price = "278.45",
                            ProductId = "93",
                            Quantity = 16,
                            Size = "small"
                        },
                        new
                        {
                            Id = 94,
                            Color = "teal",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Tasty Wooden Towels",
                            Price = "465.76",
                            ProductId = "94",
                            Quantity = 39,
                            Size = "large"
                        },
                        new
                        {
                            Id = 95,
                            Color = "ivory",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Rustic Rubber Sausages",
                            Price = "603.27",
                            ProductId = "95",
                            Quantity = 14,
                            Size = "small"
                        },
                        new
                        {
                            Id = 96,
                            Color = "ivory",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Rustic Cotton Cheese",
                            Price = "139.33",
                            ProductId = "96",
                            Quantity = 93,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 97,
                            Color = "ivory",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Refined Steel Hat",
                            Price = "683.06",
                            ProductId = "97",
                            Quantity = 51,
                            Size = "large"
                        },
                        new
                        {
                            Id = 98,
                            Color = "black",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Sleek Cotton Bacon",
                            Price = "299.82",
                            ProductId = "98",
                            Quantity = 62,
                            Size = "small"
                        },
                        new
                        {
                            Id = 99,
                            Color = "maroon",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Awesome Granite Chair",
                            Price = "114.40",
                            ProductId = "99",
                            Quantity = 72,
                            Size = "medium"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
